model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    model:
      class_path: rslearn.models.singletask.SingleTaskModel
      init_args:
        encoder:
          - class_path: rslearn.models.olmoearth_pretrain.model.OlmoEarth
            init_args:
              model_id: "OLMOEARTH_V1_TINY"
              patch_size: 4
              selector: ["encoder"]
        decoder:
            - class_path: rslearn.train.tasks.embedding.EmbeddingHead
              init_args:
                feature_map_index: 0
    lr: 0.0001
    plateau: true
    plateau_factor: 0.2
    plateau_patience: 2
    plateau_min_lr: 0
    plateau_cooldown: 10
data:
  class_path: rslearn.train.data_module.RslearnDataModule
  init_args:
    path: ${DATASET_PATH}
    inputs:
      sentinel2_l2a:
          data_type: "raster"
          layers: [
                  "sentinel2_l2a_t0",
                  ]
          bands: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B8A", "B11", "B12", "B01", "B09"]
          passthrough: true
          dtype: FLOAT32
          load_all_layers: true
          load_all_item_groups: true
      label:
        data_type: "raster"
        layers: ["label"]
        bands: ["label"]
        dtype: INT32
        is_target: true
    task:
      # The EmbeddingTask is a dummy task setup so that the output feature map can be
      # written to the rslearn dataset during `model predict`.
      # burnscar_segmentation:
      class_path: rslearn.train.tasks.embedding.EmbeddingTask
    batch_size: 1
    num_workers: ${NUM_WORKERS}
    default_config:
      transforms:
        - class_path: rslearn.models.olmoearth_pretrain.norm.OlmoEarthNormalize
          init_args:
            band_names:
              sentinel2_l2a: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B8A", "B11", "B12", "B01", "B09"]
      patch_size: 64
    train_config:
      groups: ["spatial_split_10km"]
      # By default (patch_size=null), data for the entire window bounds is read. This
      # can be cropped using transforms, but if a random crop is desired, it is more
      # efficient to crop it with this option, since this way the cropping will happen
      # when reading GeoTIFFs. However, setting it here is less flexible, since it only
      # supports random cropping.
      patch_size: 64
      # For validation, testing, and prediction, patch_size can be combined with
      # load_all_crops to perform sliding window inference. For training, it should
      # usually be left false so that each training epoch sees a different crop.
      load_all_patches: false # randomly select new patches every epoch from full size image
      # This should typically be enabled for predict_config, so that windows without
      # layers containing targets are skipped. For training, validation, and testing,
      # targets are needed so it should be false.
      skip_targets: false
      # split by tag in metadata.json
      tags:
        split: "train"
    val_config:
      groups: ["spatial_split_10km"]
      patch_size: 64
      load_all_patches: true #tmp
      tags:
        split: "val"
    test_config:
      groups: ["spatial_split_10km"]
      patch_size: 64
      load_all_patches: true
      tags:
        split: "test"
    predict_config:
      groups: ["spatial_split_10km"]
      patch_size: 64
      load_all_patches: true
      overlap_ratio: 0.5  # 16 / 64
trainer:
  max_epochs: 100
  check_val_every_n_epoch: 5
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: ${TRAINER_DATA_PATH}
        save_top_k: 1
        save_last: true
        monitor: val_loss
        mode: min
    - class_path: rslearn.train.callbacks.freeze_unfreeze.FreezeUnfreeze
      init_args:
        module_selector: ["model", "encoder", 0]
        unfreeze_at_epoch: 10
        unfreeze_lr_factor: 10
    - class_path: rslearn.train.prediction_writer.RslearnWriter
      init_args:
        path: placeholder
        output_layer: embeddings
        merger:
          class_path: rslearn.train.prediction_writer.RasterMerger
          init_args:
            # This lets the merger know what output resolution to expect relative to
            # the window's resolution. Here, our output will be 1/patch_size relative
            # to the window resolution (input resolution), since we compute one
            # embedding per patch in the input, so we set the downsample_factor to
            # patch_size.
            downsample_factor: 4 #must match patch size!!! otherwise null region present in embedding raster
            padding: 0
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: ${WANDB_PROJECT}
      name: ${WANDB_NAME}
      entity: ${WANDB_ENTITY}
# unused: ${EXTRA_FILES_PATH}
